In [1]:
# One input

In [2]:
weight = 0.1

In [3]:
def neural_network(input, weight):
    prediction = input * weight
    return prediction

In [4]:
number_of_toes = [8.5, 9.5, 10, 9]

In [5]:
input = number_of_toes[0]

In [6]:
prediction = neural_network(input, weight)

In [7]:
print(prediction)

0.8500000000000001


In [8]:
# Multiple inputs

In [9]:
weights = [0.1, 0.2, 0]

In [10]:
def weighted_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

In [11]:
def neural_network_multiple_inputs(input, weights):
    prediction = weighted_sum(input, weights)
    return prediction

In [12]:
toes = [8.5, 9.5, 9.9, 9.0]

In [13]:
win_loss_record = [0.65, 0.8, 0.8, 0.9]

In [14]:
number_of_fans = [1.2, 1.3, 0.5, 1.0] # millions

In [15]:
input = [toes[0], win_loss_record[0], number_of_fans[0]]

In [16]:
prediction = neural_network_multiple_inputs(input, weights)

In [17]:
print(prediction)

0.9800000000000001


In [18]:
# Vector maths

In [19]:
def elementwise_multiplication(vector_1, vector_2):
    assert(len(vector_1) == len(vector_2))
    return [a * b for (a, b) in zip(vector_1, vector_2)]

In [20]:
elementwise_multiplication([2, 4], [3, 5])

[6, 20]

In [21]:
def elementwise_addition(vector_1, vector_2):
    assert(len(vector_1) == len(vector_2))
    return [a + b for (a, b) in zip(vector_1, vector_2)]

In [22]:
elementwise_addition([2, 4], [3, 5])

[5, 9]

In [23]:
def vector_sum(vector):
    result = 0
    for n in vector:
        result += n
    return result

In [24]:
vector_sum([4, 9])

13

In [25]:
def vector_average(vector):
    sum = vector_sum(vector)
    return sum / len(vector)

In [26]:
vector_average([6, 13])

9.5

In [27]:
def dot_product(vector_1, vector_2):
    multiplied = elementwise_multiplication(vector_1, vector_2)
    summed = vector_sum(multiplied)
    return summed

In [28]:
dot_product([8.5, 0.65, 1.2], [0.1, 0.2, 0])

0.9800000000000001

In [29]:
# Using numpy

In [30]:
import numpy as np

In [31]:
weights = np.array([0.1, 0.2, 0])

In [32]:
def neural_network_numpy(input, weights):
    prediction = input.dot(weights)
    return prediction

In [33]:
toes = np.array([8.5, 9.5, 9.9, 9.0])

In [34]:
win_loss_record = np.array([0.65, 0.8, 0.8, 0.9])

In [35]:
number_of_fans = np.array([1.2, 1.3, 0.5, 1.0])

In [36]:
input = np.array([toes[0], win_loss_record[0], number_of_fans[0]])

In [37]:
prediction = neural_network_numpy(input, weights)

In [38]:
print(prediction)

0.9800000000000001


In [39]:
# Multiple outputs

In [40]:
weights = [0.3, 0.2, 0.9]

In [41]:
def element_multiplication(n, vector):
    return [n * v for v in vector]

In [42]:
def neural_network_multiple_outputs(input, weights):
    prediction = element_multiplication(input, weights)
    return prediction

In [43]:
win_loss_record = [0.65, 0.8, 0.8, 0.9]

In [44]:
input = win_loss_record[0]

In [45]:
prediction = neural_network_multiple_outputs(input, weights)

In [46]:
print(prediction)

[0.195, 0.13, 0.5850000000000001]


In [47]:
# Multiple inputs and multiple outputs

In [48]:
weights = [
    #toes %win #fans
    [0.1, 0.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1] # sad?
]

In [49]:
toes = [8.5, 9.5, 9.9, 9.0]

In [50]:
win_loss_record = [0.65, 0.8, 0.8, 0.9]

In [51]:
number_of_fans = [1.2, 1.3, 0.5, 1.0]

In [52]:
input = [toes[0], win_loss_record[0], number_of_fans[0]]

In [53]:
def vector_matrix_multiplication(vector, matrix):
    assert(len(vector) == len(matrix))
    return [dot_product(vector, m) for m in matrix]

In [54]:
def neural_network_multiple_inputs_and_outputs(input, weights):
    prediction = vector_matrix_multiplication(input, weights)
    return prediction

In [55]:
prediction = neural_network_multiple_inputs_and_outputs(input, weights)

In [56]:
print(prediction)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [57]:
# Hidden layer

In [58]:
weight_input_hidden = [
    #toes %win #fans
    [0.1, 0.2, -0.1], # hidden[0]
    [-0.1, 0.1, 0.9], # hidden[1]
    [0.1, 0.4, 0.1], # hidden[2]
]

In [59]:
weight_hidden_prediction = [
    #h[0] h[1] h[2]
    [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1], # sad?
]

In [60]:
weights = [weight_input_hidden, weight_hidden_prediction]

In [61]:
def neural_network_hidden_layer(input, weights):
    hidden = vector_matrix_multiplication(input, weights[0])
    prediction = vector_matrix_multiplication(hidden, weights[1])
    return prediction

In [62]:
prediction = neural_network_hidden_layer(input, weights)

In [63]:
print(prediction)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [64]:
# Hidden layer with numpy

In [65]:
weight_input_hidden = np.array([
    #toes %win #fans
    [0.1, 0.2, -0.1], # hidden[0]
    [-0.1, 0.1, 0.9], # hidden[1]
    [0.1, 0.4, 0.1], # hidden[2]
]).T

In [66]:
weight_hidden_prediction = np.array([
    #h[0] h[1] h[2]
    [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1], # sad?
]).T

In [67]:
weights = [weight_input_hidden, weight_hidden_prediction]

In [68]:
def neural_network_hidden_layer_numpy(input, weights):
    hidden = input.dot(weights[0])
    prediction = hidden.dot(weights[1])
    return prediction

In [69]:
input = np.array([toes[0], win_loss_record[0], number_of_fans[0]])

In [70]:
prediction = neural_network_hidden_layer_numpy(input, weights)

In [71]:
print(prediction)

[0.2135 0.145  0.5065]


In [72]:
# numpy primer

In [73]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([
    [0,1,2,3],
    [4,5,6,7]
])
d = np.zeros((2,4))
e = np.random.rand(2,5)

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.88387405 0.08041039 0.36255877 0.14270463 0.46582081]
 [0.80992283 0.77711668 0.94185163 0.36711901 0.25480716]]


In [74]:
print(a * 0.1)
print(c * 0.2)
print(a * b)
print(a * b * 0.2)
print(a * c)

# Errors because a and elements of e do not have the same number of columns
# print(a * e)

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [75]:
a = np.zeros((1, 4))
b = np.zeros((4, 3))
c = a.dot(b)
print(c.shape)

(1, 3)


In [76]:
a = np.zeros((2, 4))
b = np.zeros((4, 3))
c = a.dot(b)
print(c.shape)

(2, 3)


In [77]:
e = np.zeros((2, 1))
f = np.zeros((1, 3))
g = e.dot(f)
print(g.shape)

(2, 3)


In [78]:
h = np.zeros((5, 4)).T
i = np.zeros((5, 6))
j = h.dot(i)
print(j.shape)

(4, 6)


In [79]:
# Throws an error without the transformation
# h = np.zeros((5, 4))
# i = np.zeros((5, 6))
# j = h.dot(i)